name: e2e tests
on:
  pull_request:
    branches:
      - development
    types: 
      - opened
      - synchronize
    paths-ignore:
      - '.github/**'
      - '**.md'
      - 'images/**'
  workflow_dispatch:

jobs:

  e2e-tests:

    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: save info to GITHUB_ENV
        run: |
          x=$(git branch) && echo "CHECKOUT_BRANCH='$x'" >> $GITHUB_ENV
          x=$(node -p 'require("./lerna.json").version' && echo "CURRENT_VERSION='$x'" >> $GITHUB_ENV
      
      - name: show env
        run: env

      - name: setup git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: setup npm credential
        run: npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: install dependencies
        run: npm install

      - name: lerna bootstrap
        run: npx lerna bootstrap

      - name: Run test
        run: npx lerna run test --stream