name: e2e plus tests
on: 
  pull_request:
    branches:
      - main
    types: 
      - opened
      - synchronize
    paths-ignore:
      - '.github/**'
      - '**.md'
      - 'images/**'
  workflow_dispatch:

jobs:

  e2e-plus-tests:

    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: git branch
        run: git branch

      - name: install dependencies
        run: npm install

      - name: lerna bootstrap
        run: npx lerna bootstrap

      - name: Run test
        run: npx lerna run test --stream

      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"