name: e2e plus tests
on: 
  pull_request:
    branches:
      - main
    types: 
      - opened
      - synchronize
    paths-ignore:
      - '.github/**'
      - '**.md'
      - 'images/**'
  workflow_dispatch:

jobs:

  e2e-plus-tests:

    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: git branch
        run: git branch

      - name: install dependencies
        run: npm install

      - name: lerna bootstrap
        run: npx lerna bootstrap

      - name: Run test
        run: npx lerna run test --stream

      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: automerge

      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_REMOVE_LABELS: "automerge"

      - name: setup git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: setup npm credential
        run: npm set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: version and publish
        run: |
          if [ "${GITHUB_REF##*/}" = main ]; then
            npx lerna version --conventional-commits --conventional-graduate --create-release --yes
          else
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          fi
          npx lerna publish from-git --yes
        env:
          GH_TOKEN: ${{ secrets.ACCESS_PASS }}