name: e2e tests
on:
  pull_request:
    branches:
      - development
    types: 
      - opened
      - synchronize
    paths-ignore:
      - '.github/**'
      - '**.md'
      - 'images/**'
  workflow_dispatch:

jobs:

  e2e-tests:

    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: show info
        run: |
          env
          cat $GITHUB_EVENT_PATH
          [ -f note.txt ] && cat note.txt

      - name: setup git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: setup npm credential
        run: npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      # - name: setup tmp branch
      #   run: |
      #     TMP_BRANCH_NAME="$(uuidgen)-e2e-test"
      #     echo "TMP_BRANCH_NAME=$TMP_BRANCH_NAME" >> $GITHUB_ENV
      #     git branch $TMP_BRANCH_NAME
      #     git checkout $GITHUB_BASE_REF
      #     git merge $TMP_BRANCH_NAME -m "merge $GITHUB_REF_NAME by e2e-test"

      - name: install dependencies
        run: npm install

      - name: lerna bootstrap
        run: npx lerna bootstrap

      - name: Run test
        run: npx lerna run test --stream

      - name: commit and push 
        run: |
          git config advice.detached head false
          git add .
          git commit -am "commit $GITHUB_REF_NAME by e2e-test"
          # git push --set-upstream origin $GITHUB_REF_NAME

      - name: merge into GITHUB_BASE_REF
        run: |
          git branch temporary-work
          git checkout $GITHUB_BASE_REF
          git merge temporary-work -m "merge $GITHUB_REF_NAME by e2e-test"
      
      - name: version && publish
        run: |
          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes --dist-tag beta --dist-tag next
          npx lerna publish from-git --yes
        env:
            GH_TOKEN: ${{ secrets.ACCESS_PASS }}