name: production release
on: 
  pull_request:
    branches:
      - main
    types: 
      - opened
      - reopened
      - synchronize
      - edited
    paths-ignore:
      - '.github/**'
      - '**.md'
      - 'images/**'
  workflow_dispatch:

jobs:

  production-release:

    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: setup git config & npm
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: install dependencies
        run: npm install

      - name: lerna bootstrap
        run: npx lerna bootstrap

      - name: Run test
        run: npx lerna run test --stream

      - name: commit and merge into GITHUB_BASE_REF
        run: |
          git config advice.detached head false
          git add .
          git commit -am "commit $GITHUB_REF_NAME by e2e-test"
          git branch temporary-work
          git checkout $GITHUB_BASE_REF
          git merge temporary-work -m "merge $GITHUB_REF_NAME by e2e-test"
      
      - name: version & publish
        run: |
          npx lerna version --conventional-commits --conventional-graduate --create-release=github --yes
          npx lerna publish from-git --yes --dist-tag latest
        env:
            GH_TOKEN: ${{ secrets.ACCESS_PASS }}

      - name: update lerna.json version to development
        run: |
          cp lerna.json /tmp
          git checkout development
          git pull
          cp /tmp/lerna.json .
          git add .
          git commit -am "update lerna.json version by product-release" || true
          git push || true