name: publish
on:
  pull_request:
    types: [closed]
    branches:
      - development
      - main
  workflow_dispatch:

jobs:
  publish:
    if: github.event.pull_request.merged == true
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: setup git config
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: setup npm credential
      run: npm set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: version and publish
      run: |
        if [ "${GITHUB_REF##*/}" = main ]; then
          npx lerna version --conventional-commits --conventional-graduate --yes
        else
          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
        fi
        npx lerna publish from-git --yes
      env:
        GH_TOKEN: ${{ secrets.ACCESS_PASS }}

    - name: get current version
      run: |
        CURRENT_VERSION=$(node -p 'require("./lerna.json").version')
        echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

    - name: create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_PASS }}
      with:
        tag_name: v${{ env.CURRENT_VERSION }}
        release_name: pfapi-v${{ env.CURRENT_VERSION }}
        body: |
          ${{ github.event.pull_request.body }}
        draft: false
        prerelease: false