name: to release
on:
  push:
    paths:
      - 'to-release.json'
    branches:
      - development

  workflow_dispatch:

jobs:

  to-release:

    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: setup
        run: |
          echo "API_URL=${{ github.api_url }}/repos/${{ github.repository }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: sync changed files
        run: |
          git checkout development
          [ -f to-release.json ] && rm to-release.json
          bin/save-files
          cp bin/apply-files /tmp
          git checkout main
          /tmp/apply-files
          git add .
          git commit -m "sync changed files by to-release" || true
          git push || true

      - name: create pull request
        run: |
          git checkout development
          bin/create-pr